server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0   #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
  zipkin:
    base-url: http://localhost:9090/    #zipkin server地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/